{{- if hasKey .Values "secret"}}
{{- if .Values.secret.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
  labels:
    app: {{.Values.metadata.name}}
    pipelineref: {{.Values.pipelineref}}
    githash: {{.Values.githash}}
data:
  {{.Values.vars.APP_NAME}}.{{.Values.ENV}}.json: >-
    {{.Values.base64secret}}
{{- end}}
{{- end}}